version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.volumes/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    user: '472'
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
      # GF_INSTALL_PLUGINS: 'grafana-clock-panel'
      # GF_SECURITY_ALLOW_EMBEDDING: true
      # GF_AUTH_ANONYMOUS_ENABLED: true
      # GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
      # GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      # GF_AUTH_ANONYMOUS_HIDE_VERSION: true
      # GF_AUTH_DISABLE_LOGIN_FORM: true
      # GF_AUTH_DISABLE_LOGIN: true
      # GF_AUTH_OAUTH_AUTO_LOGIN: true
    volumes:
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./.volumes/grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
