global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: vqs
    scrape_interval: 5s
    static_configs:
      - targets:
          - vqs:1337

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
