object_storage:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "./tmp"

scrape_configs:
  - job_name: "vqs"
    scrape_interval: "10s"
    static_configs:
      - targets: ["vqs:1337"]
    profiling_config:
      pprof_config:
        memory:
          enabled: false
        block:
          enabled: false
        goroutine:
          enabled: false
        mutex:
          enabled: false
        fgprof:
          enabled: false
