package constants

const (
	MAGIC_NUMBER            = 0x01535156 // VQS (0x56 0x51 0x53) Followed By 0x01 (version 1) in reversed order becase we use little endianness
	HEADER_SIZE             = 16 << 10   // 16KB
	INITIAL_QUEUE_FILE_SIZE = 128 << 20  // 128MB
	MMAP_BUFFER_SIZE        = 1 << 20    // 1MB
	MAX_HEADER_TAGS_SIZE    = 16350
)

// TODO add file version info
const (
	FILE_HEADER_MAGIC_NUMBER_OFFSET        = 0
	FILE_HEADER_TOTAL_CAPACITY_LEFT_OFFSET = FILE_HEADER_MAGIC_NUMBER_OFFSET + 4
	FILE_HEADER_COUNT_OFFSET               = FILE_HEADER_TOTAL_CAPACITY_LEFT_OFFSET + 4
	FILE_HEADER_READ_OFFSET                = FILE_HEADER_COUNT_OFFSET + 4
	FILE_HEADER_WRITE_OFFSET               = FILE_HEADER_READ_OFFSET + 4
	FILE_HEADER_DELAY_SECONDS_OFFSET       = FILE_HEADER_WRITE_OFFSET + 4
	FILE_HEADER_MAX_MESSAGE_SIZE_OFFSET    = FILE_HEADER_DELAY_SECONDS_OFFSET + 2
	FILE_HEADERM_MESSAGE_RETENTION_OFFSET  = FILE_HEADER_MAX_MESSAGE_SIZE_OFFSET + 4
	FILE_HEADER_MESSAGE_WAIT_OFFSET        = FILE_HEADERM_MESSAGE_RETENTION_OFFSET + 4
	FILE_HEADER_VISIBLITY_TIMEOUT_OFFSET   = FILE_HEADER_MESSAGE_WAIT_OFFSET + 2
	FILE_HEADER_TAGS_OFFSET                = FILE_HEADER_VISIBLITY_TIMEOUT_OFFSET + 2
	FILE_DATA_OFFSET                       = HEADER_SIZE
)
